name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  pull_request_main:
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: guideappdb
          POSTGRES_USER: guideappuser
          POSTGRES_PASSWORD: guideapp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run Migrations
        run: npm run migration:run
        env:
          DATABASE_USERNAME: guideappuser
          DATABASE_PASSWORD: guideapp
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 5432
          DATABASE_NAME: guideappdb
      - name: Run E2E Tests
        run: npm run test:e2e
      - name: Run Build
        run: npm run build